/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Output.Submenu;

import Database.Categories;
import Output.MainFrame;
import Output.Submenu.Buku.FormBuku;
import Output.Submenu.Buku.FormEditBuku;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.TypedQuery;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milea
 */
public class CariKategori extends MainFrame {

    int userId;
    Object obj;
    ArrayList<Integer> listKategoriId = new ArrayList<>();
    ArrayList<Integer> listSelectedKategoriId = new ArrayList<>();
    int tempSelectedCategory;

    /**
     * Creates new form Kategori
     */
    public CariKategori() {
//        initComponents();
    }

    public CariKategori(Object obj, int userId) {
        this.userId = userId;
        this.obj = obj;
        initComponents();
        loadTable();
        loadSelectedTable();
    }

    public void loadTable() {
        String search = inputSearch.getText().trim();
        if (search.equalsIgnoreCase("search")) {
            search = "";
        }

        TypedQuery<Categories> queryListStudents = null;

        queryListStudents = entityManager.createNamedQuery("Categories.findByLikeNama", Categories.class);
        queryListStudents.setParameter("parameter", "%" + search + "%");
        List<Categories> listKategori = queryListStudents.getResultList();
        System.out.println(listKategori.size());
        listKategoriId.clear();
        DefaultTableModel model = (DefaultTableModel) tabelListKategori.getModel();
        model.setRowCount(0);
        int i = 1;
        for (Categories data : listKategori) {
            Object[] baris = new Object[2];
            baris[0] = i++;
            listKategoriId.add(data.getKategoriId());
            baris[1] = data.getNama();
            model.addRow(baris);
        }
    }

    public void loadSelectedTable() {
        DefaultTableModel model = (DefaultTableModel) tabelKategoriYangDipilih.getModel();
        model.setRowCount(0);
        int i = 1;
        for (Integer listSelected : listSelectedKategoriId) {
            Object[] baris = new Object[2];
            baris[0] = i++;

            TypedQuery<Categories> queryListStudents = entityManager.createNamedQuery("Categories.findByKategoriId", Categories.class);
            queryListStudents.setParameter("kategoriId", listSelected);
            Categories listKategori = queryListStudents.getSingleResult();

            baris[1] = listKategori.getNama();
            model.addRow(baris);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKategoriYangDipilih = new javax.swing.JTable();
        btnTambahKategori = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelListKategori = new javax.swing.JTable();
        btnSelesai = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        inputNamaKategori = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/logo-30x30.png"))); // NOI18N
        jLabel1.setText("Cari Kategori Buku");

        btnAdd.setBackground(new java.awt.Color(255, 204, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/add-30x30.png"))); // NOI18N
        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tabelKategoriYangDipilih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Kategori"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelKategoriYangDipilih);
        if (tabelKategoriYangDipilih.getColumnModel().getColumnCount() > 0) {
            tabelKategoriYangDipilih.getColumnModel().getColumn(0).setResizable(false);
            tabelKategoriYangDipilih.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelKategoriYangDipilih.getColumnModel().getColumn(1).setResizable(false);
        }

        btnTambahKategori.setBackground(new java.awt.Color(255, 204, 0));
        btnTambahKategori.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahKategori.setText("Pilih Kategori >>");
        btnTambahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKategoriActionPerformed(evt);
            }
        });

        tabelListKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Kategori"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelListKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListKategoriMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelListKategori);
        if (tabelListKategori.getColumnModel().getColumnCount() > 0) {
            tabelListKategori.getColumnModel().getColumn(0).setResizable(false);
            tabelListKategori.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelListKategori.getColumnModel().getColumn(1).setResizable(false);
        }

        btnSelesai.setBackground(new java.awt.Color(255, 204, 0));
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        inputSearch.setText("Search");
        inputSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputSearchKeyPressed(evt);
            }
        });

        inputNamaKategori.setText("Masukkan Kategori");
        inputNamaKategori.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNamaKategoriFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNamaKategoriFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(btnTambahKategori))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputNamaKategori)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelesai))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(inputSearch))
                    .addComponent(inputNamaKategori))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String namaKategori = inputNamaKategori.getText().trim();
        if (namaKategori.isEmpty() || namaKategori.equals("Masukkan Kategori")) {
            this.peringatan("Nama Kategori tidak boleh kosong");
        } else {
            try {
                entityManager.getTransaction().begin();
                Categories newCategory = new Categories();
                newCategory.setNama(namaKategori);
                entityManager.persist(newCategory);
                entityManager.getTransaction().commit();
                this.peringatan("Berhasil menambahkan kategori!");
                inputNamaKategori.setText("Masukkan Kategori");
                this.loadTable();
            } catch (Exception e) {
                this.peringatan("Gagal menambahkan kategori!");
                entityManager.getTransaction().rollback();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void inputNamaKategoriFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNamaKategoriFocusGained
        // TODO add your handling code here:
        if (inputNamaKategori.getText().trim().equals("Masukkan Kategori")) {
            inputNamaKategori.setText("");
        }
    }//GEN-LAST:event_inputNamaKategoriFocusGained

    private void inputNamaKategoriFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNamaKategoriFocusLost
        // TODO add your handling code here:
        if (inputNamaKategori.getText().trim().equals("")) {
            inputNamaKategori.setText("Masukkan Kategori");
        }
    }//GEN-LAST:event_inputNamaKategoriFocusLost

    private void tabelListKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListKategoriMouseClicked
        // TODO add your handling code here:
        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();
        int indexId = Integer.parseInt(target.getModel().getValueAt(row, 0).toString());
        this.tempSelectedCategory = listKategoriId.get(indexId - 1);
    }//GEN-LAST:event_tabelListKategoriMouseClicked

    private void inputSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.loadTable();
        }
    }//GEN-LAST:event_inputSearchKeyPressed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        if (obj instanceof FormBuku) {
            ((FormBuku) obj).setKategoriBuku(listSelectedKategoriId);
        }else if (obj instanceof FormEditBuku) {
            ((FormEditBuku) obj).setKategoriBuku(listSelectedKategoriId);
        }else{
            System.out.println("Ini bukan instance FormBuku!");
        }
        this.dispose();
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnTambahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKategoriActionPerformed
        // TODO add your handling code here:
        this.listSelectedKategoriId.add(tempSelectedCategory);
        loadSelectedTable();
    }//GEN-LAST:event_btnTambahKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambahKategori;
    private javax.swing.JTextField inputNamaKategori;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelKategoriYangDipilih;
    private javax.swing.JTable tabelListKategori;
    // End of variables declaration//GEN-END:variables
}
