/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Output.Submenu;

import Output.Auth.FormLogin;
import Output.Submenu.Mahasiswa.CariPenyumbangBuku;
import View.BookNew;
import View.Mahasiswa;
import View.Peminjaman;
import View.TesisView;
import View.UsersView;

/**
 *
 * @author milea
 */
public class Dashboard extends javax.swing.JFrame {

    int userId;

    public Dashboard(int userId) {
        initComponents();
        panelMain.removeAll();
        panelMain.add(new View.Dashboard(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
        this.userId = userId;
    }

    public Dashboard(int userId, String panel) {
        this.userId = userId;
        initComponents();
        if (panel.equalsIgnoreCase("Books")) {
            panelMain.removeAll();
            panelMain.add(new BookNew(this, userId));
            panelMain.repaint();
            panelMain.revalidate();
        } else if (panel.equalsIgnoreCase("Thesis")) {
            panelMain.removeAll();
            panelMain.add(new TesisView(this, userId));
            panelMain.repaint();
            panelMain.revalidate();
        } else if (panel.equalsIgnoreCase("Students")) {
            panelMain.removeAll();
            panelMain.add(new Mahasiswa(this, userId));
            panelMain.repaint();
            panelMain.revalidate();
        }
    }
    
    public void redirectToBuku(int userId, String kategori){
        panelMain.removeAll();
        panelMain.add(new BookNew(this, userId, kategori));
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void redirectToBuku(int userId){
        panelMain.removeAll();
        panelMain.add(new BookNew(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void redirectToSkripsi(int userId){
        panelMain.removeAll();
        panelMain.add(new TesisView(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void redirectToPeminjaman(int userId){
        panelMain.removeAll();
        panelMain.add(new Peminjaman(userId));
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void redirectToPeminjam(int userId){
        panelMain.removeAll();
        panelMain.add(new Mahasiswa(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        panelMain.add(new View.Dashboard());
        panelMain.repaint();
        panelMain.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        menuBar1 = new javax.swing.JMenuBar();
        menuLanjutan = new javax.swing.JMenu();
        dataMahasiswa = new javax.swing.JMenuItem();
        kategori = new javax.swing.JMenuItem();
        dataUser = new javax.swing.JMenuItem();
        menuDashboard = new javax.swing.JMenu();
        menuBuku = new javax.swing.JMenu();
        dataBuku = new javax.swing.JMenuItem();
        menuSkripsi = new javax.swing.JMenu();
        dataSkripsi = new javax.swing.JMenuItem();
        menuPeminjaman = new javax.swing.JMenu();
        dataPeminjaman = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SI Buku");
        setResizable(false);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setPreferredSize(new java.awt.Dimension(1240, 680));
        panelMain.setLayout(new java.awt.BorderLayout());

        menuLanjutan.setText("Pengaturan");

        dataMahasiswa.setText("Data Mahasiswa");
        dataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataMahasiswaActionPerformed(evt);
            }
        });
        menuLanjutan.add(dataMahasiswa);

        kategori.setText("Kategori");
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });
        menuLanjutan.add(kategori);

        dataUser.setText("Users");
        dataUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataUserActionPerformed(evt);
            }
        });
        menuLanjutan.add(dataUser);

        menuBar1.add(menuLanjutan);

        menuDashboard.setText("Dashboard");
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
        });
        menuBar1.add(menuDashboard);

        menuBuku.setText("Buku");

        dataBuku.setText("Data Buku");
        dataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBukuActionPerformed(evt);
            }
        });
        menuBuku.add(dataBuku);

        menuBar1.add(menuBuku);

        menuSkripsi.setText("Skripsi");

        dataSkripsi.setText("Data Skripsi");
        dataSkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSkripsiActionPerformed(evt);
            }
        });
        menuSkripsi.add(dataSkripsi);

        menuBar1.add(menuSkripsi);

        menuPeminjaman.setText("Peminjaman");

        dataPeminjaman.setText("Data Peminjaman");
        dataPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPeminjamanActionPerformed(evt);
            }
        });
        menuPeminjaman.add(dataPeminjaman);

        menuBar1.add(menuPeminjaman);

        setJMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        // TODO add your handling code here:
        new FormKategori(userId).setVisible(true);
    }//GEN-LAST:event_kategoriActionPerformed

    private void dataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataMahasiswaActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(new Mahasiswa(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_dataMahasiswaActionPerformed

    private void dataPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPeminjamanActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(new Peminjaman(userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_dataPeminjamanActionPerformed

    private void dataSkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSkripsiActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(new TesisView(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_dataSkripsiActionPerformed

    private void dataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBukuActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(new BookNew(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_dataBukuActionPerformed

    private void dataUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataUserActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(new UsersView(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_dataUserActionPerformed

    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(new View.Dashboard(this, userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_menuDashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dataBuku;
    private javax.swing.JMenuItem dataMahasiswa;
    private javax.swing.JMenuItem dataPeminjaman;
    private javax.swing.JMenuItem dataSkripsi;
    private javax.swing.JMenuItem dataUser;
    private javax.swing.JMenuItem kategori;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenu menuBuku;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JMenu menuLanjutan;
    private javax.swing.JMenu menuPeminjaman;
    private javax.swing.JMenu menuSkripsi;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
