/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Output;

import View.PanelBuku;
import View.PanelBukuNew;
import View.PanelSkripsi;

/**
 *
 * @author milea
 */
public class MenuUtama extends javax.swing.JFrame {

    int userID;

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    public MenuUtama(int userID) {
        initComponents();
        this.userID = userID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JPanel();
        menuDashboard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBooks = new javax.swing.JPanel();
        menuDashboard1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThesis = new javax.swing.JPanel();
        menuDashboard2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUserManagement = new javax.swing.JPanel();
        menuDashboard3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLog = new javax.swing.JPanel();
        menuDashboard4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelNavbar = new javax.swing.JPanel();
        panelCode = new javax.swing.JPanel();
        panelMainCode = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - SI Buku");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        panelSidebar.setBackground(new java.awt.Color(250, 204, 21));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 420));

        labelLogo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/logo-50x50.png"))); // NOI18N
        labelLogo.setText("SI Buku");

        btnDashboard.setBackground(new java.awt.Color(250, 204, 21));

        menuDashboard.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuDashboard.setForeground(new java.awt.Color(255, 255, 255));
        menuDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuDashboard.setText("Dashboard");
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/home-30x30.png"))); // NOI18N

        javax.swing.GroupLayout btnDashboardLayout = new javax.swing.GroupLayout(btnDashboard);
        btnDashboard.setLayout(btnDashboardLayout);
        btnDashboardLayout.setHorizontalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnDashboardLayout.setVerticalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBooks.setBackground(new java.awt.Color(250, 204, 21));
        btnBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBooksMouseClicked(evt);
            }
        });

        menuDashboard1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuDashboard1.setForeground(new java.awt.Color(255, 255, 255));
        menuDashboard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuDashboard1.setText("Books");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/books-30x30.png"))); // NOI18N

        javax.swing.GroupLayout btnBooksLayout = new javax.swing.GroupLayout(btnBooks);
        btnBooks.setLayout(btnBooksLayout);
        btnBooksLayout.setHorizontalGroup(
            btnBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuDashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBooksLayout.setVerticalGroup(
            btnBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuDashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThesis.setBackground(new java.awt.Color(250, 204, 21));
        btnThesis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThesisMouseClicked(evt);
            }
        });

        menuDashboard2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuDashboard2.setForeground(new java.awt.Color(255, 255, 255));
        menuDashboard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuDashboard2.setText("Thesis");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/journal-30x30.png"))); // NOI18N

        javax.swing.GroupLayout btnThesisLayout = new javax.swing.GroupLayout(btnThesis);
        btnThesis.setLayout(btnThesisLayout);
        btnThesisLayout.setHorizontalGroup(
            btnThesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnThesisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuDashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnThesisLayout.setVerticalGroup(
            btnThesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnThesisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnThesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuDashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUserManagement.setBackground(new java.awt.Color(250, 204, 21));

        menuDashboard3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuDashboard3.setForeground(new java.awt.Color(255, 255, 255));
        menuDashboard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuDashboard3.setText("User Management");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/user-management-30x30.png"))); // NOI18N

        javax.swing.GroupLayout btnUserManagementLayout = new javax.swing.GroupLayout(btnUserManagement);
        btnUserManagement.setLayout(btnUserManagementLayout);
        btnUserManagementLayout.setHorizontalGroup(
            btnUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUserManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuDashboard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUserManagementLayout.setVerticalGroup(
            btnUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuDashboard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLog.setBackground(new java.awt.Color(250, 204, 21));

        menuDashboard4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuDashboard4.setForeground(new java.awt.Color(255, 255, 255));
        menuDashboard4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuDashboard4.setText("Log");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/log-30x30.png"))); // NOI18N

        javax.swing.GroupLayout btnLogLayout = new javax.swing.GroupLayout(btnLog);
        btnLog.setLayout(btnLogLayout);
        btnLogLayout.setHorizontalGroup(
            btnLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuDashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLogLayout.setVerticalGroup(
            btnLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuDashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("ADMIN AREA");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("USER AREA");

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnThesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(btnUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.BorderLayout());

        panelNavbar.setBackground(new java.awt.Color(250, 204, 21));
        panelNavbar.setPreferredSize(new java.awt.Dimension(630, 25));

        javax.swing.GroupLayout panelNavbarLayout = new javax.swing.GroupLayout(panelNavbar);
        panelNavbar.setLayout(panelNavbarLayout);
        panelNavbarLayout.setHorizontalGroup(
            panelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panelNavbarLayout.setVerticalGroup(
            panelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        panelMain.add(panelNavbar, java.awt.BorderLayout.PAGE_START);

        panelCode.setBackground(new java.awt.Color(204, 204, 255));

        panelMainCode.setBackground(new java.awt.Color(255, 255, 255));
        panelMainCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        panelMainCode.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelCodeLayout = new javax.swing.GroupLayout(panelCode);
        panelCode.setLayout(panelCodeLayout);
        panelCodeLayout.setHorizontalGroup(
            panelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMainCode, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCodeLayout.setVerticalGroup(
            panelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMainCode, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMain.add(panelCode, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBooksMouseClicked
        // TODO add your handling code here:
        panelMainCode.removeAll();
        panelMainCode.add(new PanelBukuNew());
        panelMainCode.repaint();
        panelMainCode.revalidate();
    }//GEN-LAST:event_btnBooksMouseClicked

    private void btnThesisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThesisMouseClicked
        // TODO add your handling code here:
        panelMainCode.removeAll();
        panelMainCode.add(new PanelSkripsi());
        panelMainCode.repaint();
        panelMainCode.revalidate();
    }//GEN-LAST:event_btnThesisMouseClicked

    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        // TODO add your handling code here:
        panelMainCode.removeAll();
        panelMainCode.add(new PanelBuku());
        panelMainCode.repaint();
        panelMainCode.revalidate();                     
    }//GEN-LAST:event_menuDashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBooks;
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JPanel btnLog;
    private javax.swing.JPanel btnThesis;
    private javax.swing.JPanel btnUserManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel menuDashboard;
    private javax.swing.JLabel menuDashboard1;
    private javax.swing.JLabel menuDashboard2;
    private javax.swing.JLabel menuDashboard3;
    private javax.swing.JLabel menuDashboard4;
    private javax.swing.JPanel panelCode;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMainCode;
    private javax.swing.JPanel panelNavbar;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
