/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author milea
 */
public class PanelTambahBuku extends javax.swing.JPanel {

    /**
     * Creates new form PanelTambahBuku
     */
    public PanelTambahBuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSaveBuku = new javax.swing.JButton();
        btnUploadBuku = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputISBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputJudul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPenerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputTahunTerbit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputSubJudul = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputPengarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputJumlahHalaman = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel1.setText("Books / Add");

        btnSaveBuku.setBackground(new java.awt.Color(250, 204, 21));
        btnSaveBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/add-30x30.png"))); // NOI18N
        btnSaveBuku.setText("Tambah");
        btnSaveBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBukuActionPerformed(evt);
            }
        });

        btnUploadBuku.setBackground(new java.awt.Color(250, 204, 21));
        btnUploadBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnUploadBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/cancel-30x30.png"))); // NOI18N
        btnUploadBuku.setText("Batalkan");
        btnUploadBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadBukuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel2.setText("ISBN");

        inputISBN.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputISBN.setText("ISBN Buku");
        inputISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));
        inputISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputISBNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel3.setText("Judul");

        inputJudul.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputJudul.setText("Judul Buku");
        inputJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));
        inputJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJudulActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel4.setText("Penerbit");

        inputPenerbit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputPenerbit.setText("Penerbit Buku");
        inputPenerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));
        inputPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPenerbitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel5.setText("Tahun Terbit");

        inputTahunTerbit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputTahunTerbit.setText("Tahun Terbit Buku");
        inputTahunTerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));
        inputTahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTahunTerbitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel6.setText("Sub Judul");

        inputSubJudul.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputSubJudul.setText("Sub Judul Buku");
        inputSubJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));
        inputSubJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSubJudulActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel7.setText("Pengarang (Pisahkan menggunakan koma)");

        inputPengarang.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputPengarang.setText("Pengarang Buku");
        inputPengarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));
        inputPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPengarangActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel8.setText("Jumlah Halaman");

        inputJumlahHalaman.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputJumlahHalaman.setText("Jumlah Halaman Buku");
        inputJumlahHalaman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 204, 21)));
        inputJumlahHalaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahHalamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnSaveBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUploadBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputSubJudul)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(inputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(inputTahunTerbit)))
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(inputJumlahHalaman)))
                            .addComponent(jLabel7))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUploadBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSubJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputJumlahHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadBukuActionPerformed

    private void btnSaveBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveBukuActionPerformed

    private void inputISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputISBNActionPerformed

    private void inputJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJudulActionPerformed

    private void inputPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPenerbitActionPerformed

    private void inputTahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTahunTerbitActionPerformed

    private void inputSubJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSubJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSubJudulActionPerformed

    private void inputPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPengarangActionPerformed

    private void inputJumlahHalamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahHalamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJumlahHalamanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveBuku;
    private javax.swing.JButton btnUploadBuku;
    private javax.swing.JTextField inputISBN;
    private javax.swing.JTextField inputJudul;
    private javax.swing.JTextField inputJumlahHalaman;
    private javax.swing.JTextField inputPenerbit;
    private javax.swing.JTextField inputPengarang;
    private javax.swing.JTextField inputSubJudul;
    private javax.swing.JTextField inputTahunTerbit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
