/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Output.Submenu.Mahasiswa;

import Database.Students;
import Output.Auth.FormLogin;
import Output.MainFrame;
import Output.Submenu.Buku.FormBuku;
import Output.Submenu.Buku.FormEditBuku;
import Output.Submenu.Peminjaman.FormPeminjaman;
import Output.Submenu.Peminjaman.FormPeminjamanSkripsi;
import Output.Tesis.FormEditTesis;
import Output.Tesis.FormTesis;
import java.util.List;
import java.util.ArrayList;
import javax.persistence.TypedQuery;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milea
 */
public class CariPenyumbangBuku extends MainFrame {

    int userId;
    Object obj;
    ArrayList<Integer> listStudentId = new ArrayList<>();
    int studentId;

    /**
     * Creates new form ListMahasiswa
     */
    public CariPenyumbangBuku() {
        initComponents();
        new FormLogin().setVisible(true);
        this.dispose();
    }

    public CariPenyumbangBuku(Object obj, int userId) {
        initComponents();
        this.userId = userId;
        this.obj = obj;
        this.loadData();
    }

    public CariPenyumbangBuku(int userId) {
        initComponents();
        this.userId = userId;
        this.loadData();
    }

    protected void loadData() {
        String search = inputSearch.getText().trim();
        if (search.equalsIgnoreCase("search")) {
            search = "";
        }
        int filter = searchBy.getSelectedIndex();
        String query = "Students.findByLikeNim";
        if (!search.equals("")) {
            if (filter == 1) {
                query = "Students.findByLikeFullname";
            } else if (filter == 2) {
                query = "Students.findByLikeAlamat";
            } else if (filter == 3) {
                query = "Students.findByLikeTelepon";
            } else if (filter == 4) {
                query = "Students.findByAngkatan";
            }
        }
        System.out.println(search);
        TypedQuery<Students> queryListStudents = null;
        if (!search.equals("")) {
            queryListStudents = entityManager.createNamedQuery(query, Students.class);
            queryListStudents.setParameter("parameter", "%" + search + "%");
        } else {
            queryListStudents = entityManager.createNamedQuery("Students.findAll", Students.class);
        }
        List<Students> listStudent = queryListStudents.getResultList();
        listStudentId.clear();
        DefaultTableModel model = (DefaultTableModel) tabelMahasiswa.getModel();
        model.setRowCount(0);
        int i = 1;
        for (Students data : listStudent) {
            Object[] baris = new Object[6];
            baris[0] = i++;
            listStudentId.add(data.getStudentId());
            baris[1] = data.getNim();
            baris[2] = data.getFullname();
            baris[3] = data.getAngkatan();
            baris[4] = data.getTelepon();
            baris[5] = data.getAlamat();
            model.addRow(baris);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        searchBy = new javax.swing.JComboBox<>();
        inputSearch = new javax.swing.JTextField();
        btnPilihMahasiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cari Penyumbang Buku");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(561, 347));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/logo-30x30.png"))); // NOI18N
        jLabel1.setText("Cari Penyumbang Buku");

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "NIM", "Nama", "Angkatan", "Telepon", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMahasiswa);
        if (tabelMahasiswa.getColumnModel().getColumnCount() > 0) {
            tabelMahasiswa.getColumnModel().getColumn(0).setResizable(false);
            tabelMahasiswa.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelMahasiswa.getColumnModel().getColumn(1).setResizable(false);
            tabelMahasiswa.getColumnModel().getColumn(2).setResizable(false);
            tabelMahasiswa.getColumnModel().getColumn(3).setResizable(false);
            tabelMahasiswa.getColumnModel().getColumn(4).setResizable(false);
            tabelMahasiswa.getColumnModel().getColumn(5).setResizable(false);
        }

        btnAdd.setBackground(new java.awt.Color(255, 204, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/add-30x30.png"))); // NOI18N
        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        searchBy.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "Nama", "Alamat", "Telepon" }));

        inputSearch.setText("Search");

        btnPilihMahasiswa.setBackground(new java.awt.Color(255, 204, 0));
        btnPilihMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnPilihMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/check-30x30.png"))); // NOI18N
        btnPilihMahasiswa.setText("Pilih Mahasiswa");
        btnPilihMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihMahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPilihMahasiswa)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnPilihMahasiswa)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new FormMahasiswa(this, userId).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPilihMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMahasiswaActionPerformed
        // TODO add your handling code here:
        System.out.println(studentId);
        if (obj instanceof FormBuku) {
            ((FormBuku) obj).setMahasiswaId(studentId);
        } else if (obj instanceof FormPeminjaman) {
            ((FormPeminjaman) obj).setMahasiswaId(studentId);
        } else if (obj instanceof FormPeminjamanSkripsi) {
            ((FormPeminjamanSkripsi) obj).setMahasiswaId(studentId);
        } else if (obj instanceof FormEditBuku) {
            ((FormEditBuku) obj).setMahasiswaId(studentId);
        } else if (obj instanceof FormTesis) {
            ((FormTesis) obj).setMahasiswaId(studentId);
        } else if (obj instanceof FormEditTesis) {
            ((FormEditTesis) obj).setMahasiswaId(studentId);
        } else {
            System.out.println("bukan instance FormBuku dan FormPeminjaman");
        }
        this.dispose();
    }//GEN-LAST:event_btnPilihMahasiswaActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        // TODO add your handling code here:
        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();
        int indexId = Integer.parseInt(target.getModel().getValueAt(row, 0).toString());
        this.studentId = listStudentId.get(indexId - 1);
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariPenyumbangBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariPenyumbangBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariPenyumbangBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariPenyumbangBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariPenyumbangBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnPilihMahasiswa;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> searchBy;
    private javax.swing.JTable tabelMahasiswa;
    // End of variables declaration//GEN-END:variables
}
